### ISSUE TITLE
getsubdomain usage issue

### ISSUE THREAD

**Issue by D3vil0p3r** [hannob/tlshelpers#6]
I'm trying to use `getsubdomain` script but the usage is not clear. If I run `getsubdomain google.com` as example, I get:
```
ERROR:  canceling statement due to conflict with recovery
DETAIL:  User query might have needed to see row versions that must be removed.
FATAL:  terminating connection due to conflict with recovery
DETAIL:  User query might have needed to see row versions that must be removed.
HINT:  In a moment you should be able to reconnect to the database and repeat your command.
google.com
```

**Comment by hannob** [comment]
That's how you use it, however it depends on the postgresql api of crt.sh. I think it just sometimes causes a timeout if there are too many results, which happens to be with large domains.
Not much I can do, but I was just able to successfully get the subdomains from google, just try again.

**Comment by D3vil0p3r** [comment]
> That's how you use it, however it depends on the postgresql api of crt.sh. I think it just sometimes causes a timeout if there are too many results, which happens to be with large domains. Not much I can do, but I was just able to successfully get the subdomains from google, just try again.

You're right. By repeating the command, it works correctly. Thanks.
