### ISSUE TITLE
ilcense change to 0BSD

### ISSUE THREAD

**Issue by hannob** [hannob/tlshelpers#7]
I tend to use the 0BSD license for all my small projects and would like to relicense this repo as well.

There seem to have been some concerns around the wording of the unlicense, although it's now OSI approved.

@mss you appear to be the only person that contributed to this repo except me, while I think it's probably not strictly necessary to ask for approval as the unlicense allows pretty much everything, I'd feel better if you could approve the license change.

**Comment by mss** [comment]
No worries, consider this a CLA to do whatever you want with my code :-)
